services:
  image-downloader:
    build: .
    container_name: image-downloader
    restart: "no"
    env_file:
      - .env
    volumes:
      - ./images:/app/images
      - ./input.csv:/app/input.csv